# Generated by Django 3.2 on 2021-04-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('emaildapessoa', models.EmailField(max_length=200, verbose_name='Qual o email')),
                ('funcaodobrother', models.CharField(blank=True, max_length=100, verbose_name='Qual a função')),
                ('cpf', models.CharField(blank=True, max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, verbose_name='Data de Nascimento')),
                ('foto_x', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Foto X')),
                ('foto_y', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Foto Y')),
                ('foto', models.ImageField(blank=True, height_field='foto_y', max_length=600, upload_to='colaboradores/fotos', width_field='foto_x')),
                ('desligado', models.BooleanField(db_index=True, default=False, verbose_name='Desligado?')),
            ],
            options={
                'verbose_name_plural': 'Colaboradores',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('oque', models.CharField(max_length=200, verbose_name='O que faz')),
                ('quem_indicou', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Quem indicou?')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
    ]
