# Generated by Django 3.2 on 2021-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='emaildapessoa',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='banco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='conta',
            field=models.CharField(blank=True, max_length=200, verbose_name='Conta'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='emailpessoal',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Qual o email pessoal'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='emailshoot',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Qual o email da Shoot'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='errege',
            field=models.CharField(blank=True, max_length=14, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='estado',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='pais',
            field=models.CharField(blank=True, max_length=200, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='salario',
            field=models.CharField(blank=True, max_length=200, verbose_name='Salário'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='telefone',
            field=models.CharField(blank=True, max_length=200, verbose_name='Fone'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome completo'),
        ),
    ]
