# Generated by Django 3.2 on 2021-04-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20210406_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qual a função'),
        ),
    ]
