# Generated by Django 3.2 on 2021-04-18 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_auto_20210417_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Empresa')),
                ('cnpjempresa', models.CharField(max_length=100, verbose_name='CNPJ')),
                ('razaosocial', models.CharField(blank=True, max_length=200, verbose_name='Razão Social')),
                ('nomecontato', models.CharField(blank=True, max_length=200, verbose_name='Líder no cliente')),
                ('emailcontato', models.CharField(blank=True, max_length=200, verbose_name='E-mail de contato')),
                ('fonecontato', models.CharField(blank=True, max_length=200, verbose_name='Fone do contato')),
                ('lidershoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Líder Shoot')),
            ],
        ),
    ]
