# Generated by Django 3.2 on 2021-04-18 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='foto_x',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Foto X'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='foto_y',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Foto Y'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(blank=True, height_field='foto_y', max_length=600, upload_to='clientes/logos', width_field='foto_x'),
        ),
    ]
