# Generated by Django 3.2 on 2021-04-07 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_colaborador_funcao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='funcao',
            new_name='funcaodobrother',
        ),
    ]
