# Generated by Django 3.2 on 2021-04-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_auto_20210418_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cnpjempresa',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=17, verbose_name='CNPJ'),
        ),
    ]
