# Generated by Django 3.2 on 2021-04-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_rename_funcao_colaborador_funcaodobrother'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='emaildapessoa',
            field=models.CharField(blank=True, max_length=200, verbose_name='Qual o email do malandro'),
        ),
    ]
