# Generated by Django 3.2 on 2021-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_auto_20210418_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, verbose_name='CNPJ'),
        ),
    ]
