# Generated by Django 3.2 on 2021-04-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0005_colaborador_emaildapessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='emaildapessoa',
            field=models.EmailField(blank=True, max_length=200, verbose_name='Qual o email do malandro'),
        ),
    ]
