# Generated by Django 3.2 on 2021-04-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0006_alter_cliente_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='cpffile',
            field=models.FileField(blank=True, max_length=600, upload_to='colaboradores/docs'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='rgfile',
            field=models.FileField(blank=True, max_length=600, upload_to='colaboradores/docs'),
        ),
    ]
