# Generated by Django 3.2 on 2021-04-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_auto_20210418_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Projeto')),
                ('oque', models.CharField(max_length=200, verbose_name='O que faz')),
            ],
        ),
    ]
