# Generated by Django 3.2 on 2021-04-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0007_alter_colaborador_emaildapessoa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='eh_negra',
        ),
    ]
