# Generated by Django 3.2 on 2021-04-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0008_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='oque',
        ),
        migrations.AddField(
            model_name='projeto',
            name='ativismo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ativismo'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='desconto',
            field=models.CharField(blank=True, max_length=100, verbose_name='Desconto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='lucro',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='numero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número da Proposta'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valorfinal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor final'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valortotal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome do Projeto'),
        ),
    ]
