# Generated by Django 3.2 on 2021-04-18 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0009_auto_20210418_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cliente', verbose_name='Cliente'),
        ),
    ]
