# Generated by Django 3.2 on 2021-04-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0011_alter_colaborador_fotinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fotinho',
            field=models.ImageField(upload_to='rh/imgs/', verbose_name='Manda fotinho ai'),
        ),
    ]
