# Generated by Django 3.2 on 2021-04-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0013_auto_20210418_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='valorfinal',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valortotal',
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor final'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor total'),
        ),
    ]
