# Generated by Django 3.2 on 2021-04-07 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_alter_colaborador_fotinho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='fotinho',
        ),
    ]
