# Generated by Django 3.2 on 2021-04-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0014_auto_20210419_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, to='rh.Colaborador'),
        ),
    ]
