# Generated by Django 3.2 on 2021-04-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_projeto_colaboradores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
