# Generated by Django 3.2 on 2021-04-07 22:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0015_remove_colaborador_fotinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fotinho',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='imgs/', verbose_name='Manda fotinho ai'),
            preserve_default=False,
        ),
    ]
