# Generated by Django 3.2 on 2021-04-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_alter_colaborador_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='lidershoot',
            new_name='lider_shoot',
        ),
        migrations.AddField(
            model_name='projeto',
            name='lider_shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider', to='rh.colaborador', verbose_name='Líder Shoot'),
        ),
    ]
