# Generated by Django 3.2 on 2021-04-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0016_colaborador_fotinho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, verbose_name='Titulo do trabalho')),
                ('cliente', models.EmailField(max_length=200, verbose_name='Cliente')),
                ('datajob', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='fotinho',
        ),
    ]
