# Generated by Django 3.2 on 2021-04-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_auto_20210419_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Projeto')),
                ('numero', models.IntegerField(blank=True, verbose_name='Número da Proposta')),
            ],
        ),
        migrations.AlterModelOptions(
            name='colaborador',
            options={'ordering': ('nome',), 'verbose_name': 'a pessoa', 'verbose_name_plural': 'Colaboradores'},
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpffile',
            field=models.FileField(blank=True, max_length=600, upload_to='colaboradores/docs', verbose_name='Foto do CPF'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='desligado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Marque aqui se essa pessoa já foi desligada'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='rgfile',
            field=models.FileField(blank=True, max_length=600, upload_to='colaboradores/docs', verbose_name='Foto do RG'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='numero',
            field=models.IntegerField(blank=True, verbose_name='Número da Proposta'),
        ),
    ]
