# Generated by Django 3.2 on 2021-04-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0017_auto_20210409_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propostas',
            name='cliente',
            field=models.CharField(max_length=200, verbose_name='Cliente'),
        ),
    ]
