# Generated by Django 3.2 on 2021-04-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0018_auto_20210420_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='ativismo',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='desconto',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='lider_shoot',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='lucro',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valor_final',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='proposta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, to='rh.Colaborador'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='lider_shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider', to='rh.colaborador', verbose_name='Líder Shoot'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor final'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor total'),
        ),
    ]
