# Generated by Django 3.2 on 2021-04-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_auto_20210420_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='proposta',
            name='ativismo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quanto pra ativismo'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='horas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas vendidas'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='lucro',
            field=models.IntegerField(blank=True, null=True, verbose_name='Lucro da Shoot'),
        ),
    ]
