# Generated by Django 3.2 on 2021-04-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0019_rename_propostas_fornecedores'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colaborador',
            options={'verbose_name_plural': 'Colaboradores'},
        ),
    ]
