# Generated by Django 3.2 on 2021-04-21 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0020_auto_20210420_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='colaboradores',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='lider_shoot',
        ),
        migrations.AddField(
            model_name='projeto',
            name='colaboradores',
            field=models.ManyToManyField(blank=True, to='rh.Colaborador'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='lider_shoot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lider', to='rh.colaborador', verbose_name='Líder Shoot'),
        ),
    ]
