# Generated by Django 3.2 on 2021-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0021_auto_20210421_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Projeto')),
                ('numero', models.IntegerField(blank=True, verbose_name='Número da Proposta')),
            ],
        ),
    ]
