# Generated by Django 3.2 on 2021-04-09 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0023_remove_colaborador_fotinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='fotinho',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img', verbose_name='Fotinho'),
            preserve_default=False,
        ),
    ]
