# Generated by Django 3.2 on 2021-04-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0024_colaborador_fotinho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='fotinho',
            new_name='image',
        ),
    ]
