# Generated by Django 3.2 on 2021-04-11 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0025_rename_fotinho_colaborador_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fornecedores',
            old_name='datajob',
            new_name='datafornecedor',
        ),
        migrations.RemoveField(
            model_name='fornecedores',
            name='cliente',
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='oque',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='O que faz'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Nome do Fornecedor'),
        ),
    ]
