# Generated by Django 3.2 on 2021-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_auto_20210411_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colaborador',
            old_name='image',
            new_name='fotinho',
        ),
    ]
