# Generated by Django 3.2 on 2021-05-15 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0026_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='cidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='email',
            field=models.CharField(blank=True, max_length=200, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='fone',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fone'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='observ',
            field=models.CharField(blank=True, max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='desligado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Status na empresa'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='oque',
            field=models.CharField(blank=True, max_length=200, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Empresa'),
        ),
    ]
