# Generated by Django 3.2 on 2021-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0027_rename_image_colaborador_fotinho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='fotinho',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
