# Generated by Django 3.2 on 2021-05-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0028_auto_20210515_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadecomercial',
            options={'verbose_name': 'Atividade'},
        ),
    ]
