# Generated by Django 3.2 on 2021-04-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0029_remove_colaborador_fotinho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedores',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
    ]
