# Generated by Django 3.2 on 2021-05-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0030_auto_20210515_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedores',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.atividadecomercial', verbose_name='Quem indicou?'),
        ),
    ]
