# Generated by Django 3.2 on 2021-04-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_auto_20210413_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedores',
            name='datafornecedor',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='desligado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Desligado?'),
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='quem_indicou',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Quem indicou?'),
        ),
    ]
