# Generated by Django 3.2 on 2021-05-15 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0031_fornecedores_atividade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atividadecomercial',
            options={'verbose_name': 'Atividade'},
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='iniciativanaobranca',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Iniciativa não-branca'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='atividade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.atividadecomercial', verbose_name='Atividade'),
        ),
    ]
