# Generated by Django 3.2 on 2021-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0032_auto_20210515_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hierarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Função')),
                ('salariobase', models.IntegerField(blank=True, max_length=200, verbose_name='Salário base')),
            ],
            options={
                'verbose_name': 'Funções',
            },
        ),
    ]
