# Generated by Django 3.2 on 2021-05-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0033_hierarquia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarquia',
            name='salariobase',
            field=models.IntegerField(blank=True, verbose_name='Salário base'),
        ),
    ]
