# Generated by Django 3.2 on 2021-05-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0035_auto_20210516_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='funcaodobrother',
            field=models.CharField(blank=True, max_length=100, verbose_name='Qual a função'),
        ),
    ]
