# Generated by Django 3.2 on 2021-05-16 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0038_auto_20210516_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='entrounashoot',
            field=models.DateField(blank=True, null=True, verbose_name='Entrou na Shoot que dia'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='desligado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Não trampa mais aqui?'),
        ),
    ]
