# Generated by Django 3.2 on 2021-05-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0039_auto_20210516_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folguinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='De quando')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Até quando')),
                ('quem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Quem')),
            ],
        ),
    ]
