# Generated by Django 3.2 on 2021-05-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0040_folguinha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folguinha',
            options={'verbose_name': 'Folguinha'},
        ),
        migrations.AlterField(
            model_name='hierarquia',
            name='salariomax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário máximo'),
        ),
        migrations.AlterField(
            model_name='hierarquia',
            name='salariomin',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário mínimo'),
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome da Pesquisa de Clima')),
                ('desc', models.CharField(blank=True, max_length=200, verbose_name='Descrição da pesquisa')),
                ('quando', models.DateField(blank=True, null=True, verbose_name='Aplicou quando')),
                ('paraquem', models.ManyToManyField(blank=True, to='rh.Colaborador')),
            ],
            options={
                'verbose_name': 'Pesquisas de clima',
            },
        ),
    ]
