# Generated by Django 3.2 on 2021-05-17 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0043_auto_20210516_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocao',
            options={'verbose_name': 'Promoção', 'verbose_name_plural': 'Promoções'},
        ),
    ]
