# Generated by Django 3.2 on 2021-05-18 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0045_colaborador_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='paraquem',
        ),
    ]
