# Generated by Django 3.2 on 2021-05-18 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0046_remove_curso_paraquem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.AlterModelOptions(
            name='clima',
            options={'verbose_name': 'Curso'},
        ),
    ]
