# Generated by Django 3.2 on 2021-05-18 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0047_auto_20210518_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clima',
            options={'verbose_name': 'Pesquisas de clima'},
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('quando', models.DateField(blank=True, null=True, verbose_name='Quando')),
                ('qual', models.CharField(blank=True, max_length=200, verbose_name='Qual curso foi?')),
                ('paraquem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.colaborador', verbose_name='Para quem')),
            ],
            options={
                'verbose_name': 'Curso',
            },
        ),
    ]
