# Generated by Django 3.2 on 2021-05-20 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0048_auto_20210518_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clima',
            options={'verbose_name_plural': 'Comunicados oficiais'},
        ),
        migrations.AlterModelOptions(
            name='folguinha',
            options={'verbose_name_plural': 'Férias e folgas'},
        ),
        migrations.AlterField(
            model_name='clima',
            name='desc',
            field=models.TextField(blank=True, max_length=200, verbose_name='Descrição do que é'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do documento para leitura'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='paraquem',
            field=models.ManyToManyField(blank=True, to='rh.Colaborador', verbose_name='Quem confirmou leitura:'),
        ),
        migrations.AlterField(
            model_name='clima',
            name='quando',
            field=models.DateField(blank=True, null=True, verbose_name='Quando foi enviado'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='funcaodobrother',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.hierarquia', verbose_name='Qual a função atual'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('quando', models.DateField(blank=True, null=True, verbose_name='Quando')),
                ('analise', models.TextField(blank=True, max_length=200, verbose_name='Análise feita')),
                ('comquem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Com quem')),
            ],
            options={
                'verbose_name_plural': 'Feedbacks',
            },
        ),
    ]
