# Generated by Django 3.2 on 2021-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0050_auto_20210522_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bio',
            field=models.TextField(null=True, verbose_name='Mini bio'),
        ),
    ]
