# Generated by Django 3.2 on 2021-05-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0051_colaborador_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='verba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Verba'),
        ),
    ]
