# Generated by Django 3.2 on 2021-05-25 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0052_curso_verba'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fim',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da relação'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Início da relação'),
        ),
    ]
