# Generated by Django 3.2 on 2021-05-25 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0054_momentoimportante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True, verbose_name='ìtulo do livro')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('imagem_x', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Imagem X')),
                ('imagem_y', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Imagem Y')),
                ('imagem', models.ImageField(blank=True, height_field='imagem_y', max_length=600, upload_to='bibilioteca/imagens', width_field='imagem_x')),
                ('recomendado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Recomendado Por')),
            ],
        ),
    ]
