# Generated by Django 3.2 on 2021-05-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0055_biblioteca'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='desc',
            field=models.TextField(null=True, verbose_name='Porque você recomenda'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título do livro'),
        ),
    ]
