# Generated by Django 3.2 on 2021-05-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0057_projeto_data_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rh.cliente', verbose_name='Cliente'),
        ),
    ]
