# Generated by Django 3.2 on 2021-05-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0058_projeto_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Está ativo?'),
        ),
    ]
