# Generated by Django 3.2 on 2021-05-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0059_projeto_ativo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clima',
            options={'ordering': ['-quando'], 'verbose_name_plural': 'Comunicados oficiais'},
        ),
        migrations.AddField(
            model_name='fornecedores',
            name='sustentavel',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Iniciativa sustentável'),
        ),
    ]
