# Generated by Django 3.2 on 2021-05-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0060_auto_20210526_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='agencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Agência'),
        ),
    ]
