# Generated by Django 3.2 on 2021-05-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0061_colaborador_agencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='bairro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='cep',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CEP'),
        ),
    ]
