# Generated by Django 3.2 on 2021-05-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0062_auto_20210526_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momentoimportante',
            name='titulo',
        ),
        migrations.AddField(
            model_name='momentoimportante',
            name='desc',
            field=models.TextField(null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='momentoimportante',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do momento'),
        ),
        migrations.AlterField(
            model_name='momentoimportante',
            name='quem',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pessoa/Cliente/Parceiro'),
        ),
    ]
