# Generated by Django 3.2 on 2021-05-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0063_auto_20210526_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesaRedonda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('assunto', models.CharField(blank=True, max_length=100, verbose_name='Assunto')),
                ('leitura', models.CharField(blank=True, max_length=100, verbose_name='Link para leitura')),
                ('quem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Quem tá propondo a conversa')),
            ],
        ),
    ]
