# Generated by Django 3.2 on 2021-05-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0064_mesaredonda'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MesaRedonda',
            new_name='PapoCabeca',
        ),
    ]
