# Generated by Django 3.2 on 2021-05-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0067_rename_papocabecao_papocabeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='papocabeca',
            name='opiniao',
            field=models.TextField(blank=True, verbose_name='Qual foi seu teto?'),
        ),
    ]
