# Generated by Django 3.2 on 2021-05-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0068_papocabeca_opiniao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papocabeca',
            options={'verbose_name_plural': 'Papo Cabeça'},
        ),
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updater', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome da Palestra')),
                ('desc', models.TextField(blank=True, verbose_name='Descrição da palestra')),
                ('quem', models.ManyToManyField(blank=True, to='rh.Colaborador', verbose_name='Quem é capaz de dar essa palestra')),
            ],
        ),
    ]
