# Generated by Django 3.2 on 2021-05-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0069_auto_20210526_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(blank=True, max_length=100, verbose_name='Qual o título do workshop?')),
                ('desc', models.TextField(blank=True, verbose_name='Breve descrição')),
                ('objetivos', models.CharField(blank=True, max_length=200, verbose_name='Quais os objetivos contemplados')),
                ('roteiro', models.TextField(blank=True, verbose_name='Qual o roteiro/metodologia')),
            ],
            options={
                'verbose_name_plural': 'Workshops',
            },
        ),
        migrations.DeleteModel(
            name='PapoCabeca',
        ),
    ]
