# Generated by Django 3.2 on 2021-05-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0070_auto_20210527_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanalProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Canal')),
                ('objetivo', models.TextField(blank=True, verbose_name='Objetivo do canal')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='Link do canal')),
            ],
            options={
                'verbose_name_plural': 'Canais Proprietários',
            },
        ),
    ]
