# Generated by Django 3.2 on 2021-05-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0071_canalproprietario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('base', models.IntegerField(blank=True, verbose_name='Número total de base')),
                ('engajamento', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Engajamento do canal')),
                ('quando', models.DateField(blank=True, null=True, verbose_name='Informação do dia')),
                ('canal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.canalproprietario', verbose_name='Canal')),
            ],
        ),
    ]
