# Generated by Django 3.2 on 2021-05-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0073_premiacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=200, verbose_name='Categoria que concorremos')),
                ('posicao', models.CharField(blank=True, max_length=200, verbose_name='Posição final')),
                ('investimento', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Investimento')),
                ('premio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.premiacao', verbose_name='Qual Prêmio')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.projeto', verbose_name='Projeto inscrito')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
