# Generated by Django 3.2 on 2021-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0074_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='quando',
            field=models.DateField(blank=True, null=True, verbose_name='Quando'),
        ),
    ]
