# Generated by Django 3.2 on 2021-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0076_certificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificacao',
            name='quando',
            field=models.DateField(blank=True, null=True, verbose_name='Quando certificamos'),
        ),
    ]
