# Generated by Django 3.2 on 2021-05-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0079_auto_20210529_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updater', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da ferramenta')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('quando', models.DateField(blank=True, null=True, verbose_name='Início da assinatura')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Investimento')),
                ('user', models.CharField(blank=True, max_length=100, null=True, verbose_name='User')),
                ('senha', models.CharField(blank=True, max_length=100, null=True, verbose_name='Pass')),
            ],
        ),
    ]
