# Generated by Django 3.2 on 2021-05-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0080_ferramenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferramenta',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Investimento anual'),
        ),
    ]
