# Generated by Django 3.2 on 2021-05-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0081_alter_ferramenta_preco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('inicio', models.DateField(blank=True, null=True, verbose_name='Lançado dia')),
                ('fim', models.DateField(blank=True, null=True, verbose_name='Valido até dia')),
                ('texto', models.TextField(blank=True, null=True, verbose_name='Visão')),
            ],
            options={
                'verbose_name_plural': 'Visão',
            },
        ),
    ]
