# Generated by Django 3.2 on 2021-05-29 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0082_visao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juridico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do documento')),
                ('urldoc', models.CharField(blank=True, max_length=200, verbose_name='URL do doc')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Pra que serve')),
            ],
            options={
                'verbose_name_plural': 'Docs Jurídicos',
            },
        ),
    ]
