# Generated by Django 3.2 on 2021-05-29 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0083_juridico'),
    ]

    operations = [
        migrations.AddField(
            model_name='juridico',
            name='proj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.projeto', verbose_name='Projeto'),
        ),
    ]
