# Generated by Django 3.2 on 2021-05-29 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0084_juridico_proj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juridico',
            name='proj',
        ),
        migrations.AddField(
            model_name='juridico',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.proposta', verbose_name='Projeto'),
        ),
    ]
