# Generated by Django 3.2 on 2021-05-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0085_auto_20210529_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juridico',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.proposta', verbose_name='Proposta'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='numero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.proposta', verbose_name='Proposta'),
        ),
    ]
