# Generated by Django 3.2 on 2021-05-30 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0086_auto_20210530_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cliente',
        ),
    ]
