# Generated by Django 3.2 on 2021-05-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0087_remove_projeto_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da ODS')),
                ('numero', models.IntegerField(blank=True, verbose_name='Número')),
                ('selo_x', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Selo X')),
                ('selo_y', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Selo Y')),
                ('selo', models.ImageField(blank=True, height_field='selo_y', max_length=600, upload_to='ods/selos', width_field='selo_x')),
                ('desc', models.TextField(null=True, verbose_name='Descrição da ODS')),
            ],
            options={
                'verbose_name_plural': 'Objetivos de Desenvolvimento Sustentável',
            },
        ),
    ]
