# Generated by Django 3.2 on 2021-05-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0089_impacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Etapa')),
                ('ordem', models.IntegerField(blank=True, verbose_name='Ordem')),
            ],
            options={
                'verbose_name_plural': 'Processos',
            },
        ),
    ]
