# Generated by Django 3.2 on 2021-06-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0092_proposta_urlproposta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Visao',
        ),
    ]
