# Generated by Django 3.2 on 2021-06-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0093_delete_visao'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('display', models.CharField(blank=True, choices=[(1, 'Me'), (2, 'Public')], default='F', max_length=1, null=True)),
                ('classificacao', models.CharField(blank=True, max_length=200, verbose_name='Classificação')),
            ],
        ),
    ]
