# Generated by Django 3.2 on 2021-06-03 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0096_auto_20210602_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroContaShoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('banco', models.CharField(blank=True, max_length=100, verbose_name='Banco')),
                ('conta', models.CharField(blank=True, max_length=20, verbose_name='Conta')),
                ('agencia', models.CharField(blank=True, max_length=100, verbose_name='Agência')),
                ('caixa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Caixa')),
                ('infos', models.TextField(blank=True, verbose_name='Outras infos')),
            ],
            options={
                'verbose_name': 'Conta',
            },
        ),
        migrations.AlterModelOptions(
            name='financeirogrupo',
            options={'verbose_name': 'Financeiro | Grupo de Conta'},
        ),
        migrations.AlterField(
            model_name='financeirogrupo',
            name='classifi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeiroclassificacao', verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='financeirogrupo',
            name='nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do grupo'),
        ),
    ]
