# Generated by Django 3.2 on 2021-06-03 12:56

from django.db import migrations, models
import django.db.models.deletion
import posix


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0097_auto_20210603_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeirocontashoot',
            options={'verbose_name': 'Financeiro | Conta'},
        ),
        migrations.CreateModel(
            name='FinanceiroSaidaSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('documento', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor')),
                ('colab', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.colaborador', verbose_name='Colaborador')),
                ('contashoot', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirocontashoot', verbose_name='Conta Shoot')),
                ('grupo', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirogrupo', verbose_name='Grupo de Contas')),
            ],
            options={
                'verbose_name': 'Financeiro | Salário',
            },
        ),
        migrations.CreateModel(
            name='FinanceiroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('documento', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento')),
                ('fornecedor', models.CharField(blank=True, max_length=200, verbose_name='Fornecedor')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor')),
                ('contashoot', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirocontashoot', verbose_name='Conta Shoot')),
                ('grupo', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirogrupo', verbose_name='Grupo de Contas')),
            ],
            options={
                'verbose_name': 'Financeiro | Saída',
            },
        ),
        migrations.CreateModel(
            name='FinanceiroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('documento', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Valor')),
                ('cliente', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.cliente', verbose_name='Cliente')),
                ('contashoot', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirocontashoot', verbose_name='Conta Shoot')),
                ('grupo', models.ForeignKey(blank=posix.truncate, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirogrupo', verbose_name='Grupo de Contas')),
            ],
            options={
                'verbose_name': 'Financeiro | Entrada',
            },
        ),
    ]
