# Generated by Django 3.2 on 2021-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0099_auto_20210603_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeirototal',
            name='urldoc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL do documento'),
        ),
    ]
