# Generated by Django 3.2 on 2021-06-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0100_financeirototal_urldoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceiroCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Financeiro | Categoria',
            },
        ),
        migrations.CreateModel(
            name='FinanceiroClassi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Classificação')),
            ],
            options={
                'verbose_name': 'Financeiro | Classificação',
            },
        ),
        migrations.AlterField(
            model_name='financeirototal',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirocategoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='financeirototal',
            name='classifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeiroclassi', verbose_name='Classificação'),
        ),
    ]
