# Generated by Django 3.2 on 2021-06-03 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0101_auto_20210603_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeirototal',
            name='categoria',
        ),
        migrations.AddField(
            model_name='financeiroclassi',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.financeirocategoria', verbose_name='Categoria'),
        ),
    ]
