# Generated by Django 3.2 on 2021-06-08 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0102_auto_20210603_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ativismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do Projeto')),
                ('resumo', models.TextField(blank=True, default='', help_text='Este campo é utilizado na apresentação dos detalhes do projeto no nosso site.', verbose_name='Um breve resumo do projeto')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Data Final')),
                ('ativo', models.BooleanField(db_index=True, default=False, verbose_name='Está ativo?')),
                ('urlasana', models.CharField(blank=True, max_length=100, verbose_name='URL do Projeto no Asana')),
                ('urlbriefing', models.CharField(blank=True, max_length=200, verbose_name='URL do Briefing')),
                ('causas', models.CharField(blank=True, max_length=200, verbose_name='Causas')),
                ('colaboradores', models.ManyToManyField(blank=True, to='rh.Colaborador', verbose_name='Equipe de apoio')),
                ('impacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.impacto', verbose_name='Impacto do job')),
                ('liders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lidershoot', to='rh.colaborador', verbose_name='Líder')),
                ('ods', models.ManyToManyField(blank=True, to='rh.Ods', verbose_name='Ods')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rh.processo', verbose_name='Etapa do processo')),
            ],
        ),
    ]
