# Generated by Django 3.2 on 2021-06-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0104_auto_20210609_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palestra',
            name='desc',
        ),
        migrations.AddField(
            model_name='palestra',
            name='cache',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Cachê'),
        ),
        migrations.AddField(
            model_name='palestra',
            name='publico',
            field=models.IntegerField(blank=True, null=True, verbose_name='Público'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='analise',
            field=models.TextField(blank=True, verbose_name='Análise feita'),
        ),
        migrations.AlterField(
            model_name='palestra',
            name='quem',
            field=models.ManyToManyField(blank=True, to='rh.Colaborador', verbose_name='Quem palestrou'),
        ),
    ]
