# Generated by Django 3.2 on 2021-06-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0105_auto_20210614_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestra',
            name='quando',
            field=models.DateField(blank=True, null=True, verbose_name='Quando'),
        ),
    ]
