# Generated by Django 3.2 on 2021-06-16 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0106_palestra_quando'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ods',
            options={'ordering': ['numero'], 'verbose_name_plural': 'Objetivos de Desenvolvimento Sustentável'},
        ),
    ]
